// Code generated by hertz generator.

package score

import (
	"buycar/biz/pack"
	"buycar/biz/service"
	"context"

	score "buycar/biz/model/score"

	"github.com/cloudwego/hertz/pkg/app"
)

// GetUserScore .
// @router /api/score [GET]
func GetUserScore(ctx context.Context, c *app.RequestContext) {
	var err error
	var req score.GetUserScoreReq
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	resp := new(score.GetUserScoreResp)
	data, err := service.NewScoreService(ctx, c).GetUserScore()
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}
	resp.Score = data

	pack.SendResponse(c, resp)
}

// PurchaseGift .
// @router /api/score/gift/purchase [POST]
func PurchaseGift(ctx context.Context, c *app.RequestContext) {
	var err error
	var req score.PurchaseGiftReq
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	resp := new(score.PurchaseGiftResp)
	err = service.NewScoreService(ctx, c).PurchaseGift(req.GiftID)
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	pack.SendResponse(c, resp)
}

// QueryGiftList .
// @router /api/score/gift/query [GET]
func QueryGiftList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req score.QueryGiftListReq
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	resp := new(score.QueryGiftListResp)
	data, err := service.NewScoreService(ctx, c).QueryGiftList()
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}
	resp.Gifts = data

	pack.SendResponse(c, resp)
}
